### ISSUE TITLE
Required file `tests/defaults.yml` is not created

### ISSUE THREAD

**Issue by simu** [projectsyn/modulesync-control#32]
When onboarding older components, the file `tests/defaults.yml` is not created leading to additional manual effort before the compnoent is fully onboarded to the modulesync component template synchronization.

## Steps to reproduce

. Onboard older component (see e.g. https://github.com/appuio/component-openshift4-ingress/pull/18 for an example)

## Actual behavior

`make test` fails because the component didn't have a `tests/defaults.yml` file before being onboarded.

## Expected behavior

A default `tests/defaults.yml` is generated by modulesync if the file is missing.

**Comment by mhutter** [comment]
Same for `tests/golden/defaults`

**Comment by simu** [comment]
`tests/golden/defaults` cannot be generated by modulesync as its contents fully depend on the component implementation, but a `make gen-golden` should do the trick (assuming that `tests/defaults.yml` exists).

**Comment by simu** [comment]
Modulesync does not have support for "Create file if it doesn't exist, but leave an existing file alone", so we can't generate an empty `tests/defaults.yml` for components which don't have one. Since most components are onboarded now, I'm closing this issue.
