### ISSUE TITLE
Current `.gitignore` may randomly ignore golden tests outputs

### ISSUE THREAD

**Issue by simu** [projectsyn/modulesync-control#77]
We currently have entries like `crds/` in the component `.gitignore`. This will also ignore paths such as `tests/golden/lib/resource-locker/resource-locker/01_resource_locker_operator_helmchart/resource-locker-operator/crds`, which is not the intention of the entry.

We should adjust the `.gitignore` in the template to explicitly make the ignores rooted, e.g. `/crds/` instead of `crds/`, to avoid ignoring subdirectories in `tests/` (or elsewhere).

**Comment by corvus-ch** [comment]
While on it, check the `.gitignore` for other cases that might suffer from the same issue.

**Comment by simu** [comment]
As far as I can see all the entries which are present by default should be rooted:

https://github.com/projectsyn/modulesync-control/blob/07981390c2020c6b2744c3c738a605b679e12888/moduleroot/.gitignore.erb#L7-L18
